### ISSUE TITLE
Decompression on server side fails due to unset 'Block Independence flag'

### ISSUE THREAD

**Issue by guidoschmidt17** [Benzinga/lz4js#11]
When reading an LZ4 frame send from a browser using lz4js the server side (using e. g. net.jpountz.lz4) throws an exception:

"Dependent block stream is unsupported (BLOCK_INDEPENDENCE must be set)"

Actually, the FLAG byte in the frame descriptor is currently set to

0b01000000 or 0x40

This leaves the 5th bit unset. This bit is for the BLOCK_INDEPENDENCE.

Changing the value for FLAG to

0b01100000 or 0x60

resolves the problem. This can be fixed by changing line 469 in lz4.js

`- dst[dIndex++] = fdVersion;`

`+ dst[dIndex++] = 0x60;`

The frame is then correctly decompressed on the server side.

**Comment by L3P3** [comment]
Would have been nice to create a PR for this but thanks anyways! :)

**Comment by guidoschmidt17** [comment]
I think it's not maintained anymore. So a manual patch is probably the way to go. It is still very useful, because it is a zero-dependency javascript library. And the "fast" compression is really good.
